realworld:
	bash run_real_world_exp.sh
	cat noisy_header movielens_noisy_* > movielens_noisy.csv
	cat bucket_header movielens_bucket_* > movielens_lastfm.csv
	cat noisy_header lastfm_noisy_* > lastfm_noisy.csv
	cat bucket_header lastfm_bucket_* > lastfm_bucket.csv

artificial:
	bash run_artificial_exp.sh

